/*
 Doncente: Magda Pineda
Universidad Juan de castellanos 
Asignatura: Programacion Orientada A Objetos
Descripcion:Clase que reprenseta la interfaz  De Usuario inicio de sesion
Fecha:9/05/2024
Autor: Daniel Mauricio Gil Sosa
 */
package vista;

import java.awt.Toolkit;
import static vista.vista_Prestamos.JTF_AñoPublicacionP;

/**
 *
 * @author Lenovo
 */
public class vista_InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form vista_InicioSesion
     */
    public vista_InicioSesion() {
        initComponents();
    }
    
    public static String Usuario="",prueba="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JC_mostrarContraseña = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        JTF_Clave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_User = new javax.swing.JTextField();
        JP_Password = new javax.swing.JPasswordField();
        JB_crearUsuario = new javax.swing.JButton();
        JB_crearUsuario1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JC_mostrarContraseña.setFont(new java.awt.Font("Segoe UI Variable", 2, 12)); // NOI18N
        JC_mostrarContraseña.setText("Mostrar Contraseña");
        JC_mostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_mostrarContraseñaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 2, 24)); // NOI18N
        jLabel5.setText("BIBLIOTECA JDC");

        JTF_Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_ClaveKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel3.setText("Contraseña:");

        JTF_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_UserActionPerformed(evt);
            }
        });
        JTF_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_UserKeyTyped(evt);
            }
        });

        JP_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JP_PasswordActionPerformed(evt);
            }
        });
        JP_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JP_PasswordKeyTyped(evt);
            }
        });

        JB_crearUsuario.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_crearUsuario.setText("Crear Usuario");
        JB_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_crearUsuarioActionPerformed(evt);
            }
        });

        JB_crearUsuario1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_crearUsuario1.setText("Acceder");
        JB_crearUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_crearUsuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTF_User, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JTF_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(38, 38, 38)
                            .addComponent(JP_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addComponent(JC_mostrarContraseña)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(JB_crearUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_crearUsuario)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JP_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JC_mostrarContraseña)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTF_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_crearUsuario)
                    .addComponent(JB_crearUsuario1))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JC_mostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_mostrarContraseñaActionPerformed
        if (JC_mostrarContraseña.isSelected()) {
            JP_Password.setEchoChar((char) 0);
        } else {
            JP_Password.setEchoChar('*');

        }
    }//GEN-LAST:event_JC_mostrarContraseñaActionPerformed

    private void JTF_ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_ClaveKeyTyped
          if (JTF_Clave.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTF_ClaveKeyTyped

    private void JTF_UserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_UserKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar())) {
            evt.consume();

        }
        if (JTF_User.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_JTF_UserKeyTyped

    private void JP_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JP_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JP_PasswordActionPerformed

    private void JP_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JP_PasswordKeyTyped
        if (JP_Password.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_JP_PasswordKeyTyped

    private void JB_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_crearUsuarioActionPerformed
        vista_RegistroUsuario vista_RegistroUsuario = new vista_RegistroUsuario();
        vista_RegistroUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_crearUsuarioActionPerformed

    private void JTF_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_UserActionPerformed

    private void JB_crearUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_crearUsuario1ActionPerformed

         Usuario=JTF_User.getText();

        String user = this.JTF_User.getText();
        String clave = this.JTF_Clave.getText();
        String userd = JTF_User.getText();
        String claved = JTF_Clave.getText();

        if (user.equals(userd) && clave.equals(claved)) {
            VistaDeUsuariosIngresados VistaDeUsuariosIngresados = new VistaDeUsuariosIngresados();
            VistaDeUsuariosIngresados.setVisible(true);
            this.setVisible(false);

        }


    }//GEN-LAST:event_JB_crearUsuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_crearUsuario;
    public javax.swing.JButton JB_crearUsuario1;
    public javax.swing.JCheckBox JC_mostrarContraseña;
    public javax.swing.JPasswordField JP_Password;
    public javax.swing.JTextField JTF_Clave;
    public javax.swing.JTextField JTF_User;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
