/*
  Doncente: Magda Pineda
Universidad Juan de castellanos 
Asignatura: Programacion Orientada A Objetos
Descripcion:Clase que reprenseta la interfaz Principal De Usuarios Ingresados
Fecha:9/05/2024
Autor: Daniel Mauricio Gil Sosa
 */
package vista;

import static vista.vista_InicioSesion.Usuario;

/**
 *
 * @author Lenovo
 */
public class VistaDeUsuariosIngresados extends javax.swing.JFrame {

    /**
     * Creates new form VistaDeUsuariosIngresados
     */
    public VistaDeUsuariosIngresados() {
        initComponents();
        
         JL_ResUsuario.setText(Usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_aceptar = new javax.swing.JButton();
        JB_aceptar1 = new javax.swing.JButton();
        JB_aceptar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JL_ResUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB_aceptar.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_aceptar.setText("Devoluciones");
        JB_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_aceptarActionPerformed(evt);
            }
        });

        JB_aceptar1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_aceptar1.setText("Registrar Libros");
        JB_aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_aceptar1ActionPerformed(evt);
            }
        });

        JB_aceptar2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_aceptar2.setText("Prestamo De Libros");
        JB_aceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_aceptar2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JB_aceptar)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JB_aceptar2)
                        .addGap(118, 118, 118))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(JB_aceptar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(JL_ResUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JL_ResUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(JB_aceptar1)
                .addGap(32, 32, 32)
                .addComponent(JB_aceptar2)
                .addGap(30, 30, 30)
                .addComponent(JB_aceptar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_aceptarActionPerformed
        vista_Devoluciones  vista_Devoluciones = new  vista_Devoluciones();
        vista_Devoluciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_aceptarActionPerformed

    private void JB_aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_aceptar1ActionPerformed
        vista_RegistroLibros vista_RegistroLibros = new vista_RegistroLibros();
        vista_RegistroLibros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_aceptar1ActionPerformed

    private void JB_aceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_aceptar2ActionPerformed
        vista_Prestamos vista_Prestamos  = new vista_Prestamos ();
        vista_Prestamos .setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_aceptar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDeUsuariosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDeUsuariosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDeUsuariosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDeUsuariosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDeUsuariosIngresados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_aceptar;
    public javax.swing.JButton JB_aceptar1;
    public javax.swing.JButton JB_aceptar2;
    public javax.swing.JLabel JL_ResUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
