/*
 Doncente: Magda Pineda
Universidad Juan de castellanos 
Asignatura: Programacion Orientada A Objetos
Descripcion:Clase que reprenseta la interfaz  De Registro de Usuario
Fecha:9/05/2024
Autor: Daniel Mauricio Gil Sosa
 */
package vista;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.ModeloSesion;

/**
 *
 * @author Lenovo
 */
public class vista_RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form vista_RegistroUsuario
     */
    public vista_RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTF_NumCel = new javax.swing.JTextField();
        JP_Passward = new javax.swing.JPasswordField();
        JB_registrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_NameUser = new javax.swing.JTextField();
        JB_back = new javax.swing.JButton();
        JB_back1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTF_NUMEROCELU = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTF_NumCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_NumCelKeyTyped(evt);
            }
        });

        JP_Passward.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JP_Passward.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JP_PasswardKeyTyped(evt);
            }
        });

        JB_registrar.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_registrar.setText("Registrar");
        JB_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_registrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE USUARIO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel2.setText("Nombre de Usuario:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel3.setText("Identificacion ");

        JTF_NameUser.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JTF_NameUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTF_NameUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_NameUserKeyTyped(evt);
            }
        });

        JB_back.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        JB_back.setText("ATRAS");
        JB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_backActionPerformed(evt);
            }
        });

        JB_back1.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        JB_back1.setText("INICIO");
        JB_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_back1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel4.setText("Numero De Cel");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel5.setText("Nueva contraseña");

        JTF_NUMEROCELU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_NUMEROCELUKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JB_back)
                            .addGap(42, 42, 42))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addGap(114, 114, 114)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_registrar)
                        .addGap(68, 68, 68)
                        .addComponent(JB_back1)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTF_NUMEROCELU, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_NumCel)
                            .addComponent(JTF_NameUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JP_Passward))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JP_Passward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTF_NUMEROCELU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(JTF_NumCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_registrar)
                    .addComponent(JB_back)
                    .addComponent(JB_back1))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_NumCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NumCelKeyTyped
      if(JTF_NumCel.getText().length()>=10)
       {
           evt.consume();
       }
    
    }//GEN-LAST:event_JTF_NumCelKeyTyped

    private void JP_PasswardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JP_PasswardKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
        if(JP_Passward.getText().length()>=10)
       {
           evt.consume();
       }
    }//GEN-LAST:event_JP_PasswardKeyTyped

    private void JB_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_registrarActionPerformed
        String nombreUsuario = JTF_NameUser.getText();

        String contraseña1 = JTF_NumCel.getText();

        // Crear una nueva instancia de ModeloUsuario y asignarla a la variable nuevoUsuario
        ModeloSesion modeloSesion = new ModeloSesion(nombreUsuario, contraseña1);

        JOptionPane.showMessageDialog(null, "Registrado con éxito");
    }//GEN-LAST:event_JB_registrarActionPerformed

    private void JTF_NameUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NameUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_NameUserKeyPressed

    private void JTF_NameUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NameUserKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar())) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (JTF_NameUser.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_JTF_NameUserKeyTyped

    private void JB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_backActionPerformed
        vista_InicioSesion vista_InicioSesion = new vista_InicioSesion ();
        vista_InicioSesion .setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_backActionPerformed

    private void JB_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_back1ActionPerformed
        vista_InicioSesion vista_InicioSesion = new vista_InicioSesion ();
        vista_InicioSesion .setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_back1ActionPerformed

    private void JTF_NUMEROCELUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NUMEROCELUKeyTyped
        
        
        
         char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
        if(JTF_NUMEROCELU.getText().length()>=10)
       {
           evt.consume();
       }
        
        
    }//GEN-LAST:event_JTF_NUMEROCELUKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_back;
    public javax.swing.JButton JB_back1;
    public javax.swing.JButton JB_registrar;
    public javax.swing.JPasswordField JP_Passward;
    private javax.swing.JTextField JTF_NUMEROCELU;
    public static javax.swing.JTextField JTF_NameUser;
    public static javax.swing.JTextField JTF_NumCel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
