/*
  Doncente: Magda Pineda
Universidad Juan de castellanos 
Asignatura: Programacion Orientada A Objetos
Descripcion:Clase que reprenseta la interfaz  De Usuario Devoluciones
Fecha:9/05/2024
Autor: Daniel Mauricio Gil Sosa
 */
package vista;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.ModeloRegistroLibros;

/**
 *
 * @author Lenovo
 */
public class vista_Devoluciones extends javax.swing.JFrame {

    /**
     * Creates new form vista_Devoluciones
     */
    public vista_Devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTF_TituloLP = new javax.swing.JTextField();
        JTF_AñoPublicacionP = new javax.swing.JTextField();
        JTF_ISBNP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JB_registrar = new javax.swing.JButton();
        JTF_AutorP = new javax.swing.JTextField();
        JB_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel3.setText("Autor");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel2.setText("Titulo");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel4.setText("Año de Publicacion");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel5.setText("ISBN");

        JTF_TituloLP.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JTF_TituloLP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTF_TituloLPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_TituloLPKeyTyped(evt);
            }
        });

        JTF_AñoPublicacionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_AñoPublicacionPActionPerformed(evt);
            }
        });
        JTF_AñoPublicacionP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_AñoPublicacionPKeyTyped(evt);
            }
        });

        JTF_ISBNP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_ISBNPKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel1.setText("Devolucion de libro");

        JB_registrar.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_registrar.setText("Devolver Libro");
        JB_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_registrarActionPerformed(evt);
            }
        });

        JTF_AutorP.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JTF_AutorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_AutorPActionPerformed(evt);
            }
        });
        JTF_AutorP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTF_AutorPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_AutorPKeyTyped(evt);
            }
        });

        JB_back.setFont(new java.awt.Font("Sitka Display", 3, 14)); // NOI18N
        JB_back.setText("ATRAS");
        JB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JTF_TituloLP)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JB_back)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_AñoPublicacionP, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(JTF_ISBNP)
                                    .addComponent(JTF_AutorP)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(JB_registrar)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_TituloLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_AutorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_AñoPublicacionP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTF_ISBNP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_back)
                    .addComponent(JB_registrar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_TituloLPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_TituloLPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_TituloLPKeyPressed

    private void JTF_TituloLPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_TituloLPKeyTyped
        if (JTF_TituloLP.getText().length() >= 10) {
            evt.consume();
        }


    }//GEN-LAST:event_JTF_TituloLPKeyTyped

    private void JTF_AñoPublicacionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_AñoPublicacionPActionPerformed

    }//GEN-LAST:event_JTF_AñoPublicacionPActionPerformed

    private void JTF_AñoPublicacionPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_AñoPublicacionPKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (JTF_AñoPublicacionP.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_JTF_AñoPublicacionPKeyTyped

    private void JTF_ISBNPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_ISBNPKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (JTF_ISBNP.getText().length() >= 13) {
            evt.consume();
        }

    }//GEN-LAST:event_JTF_ISBNPKeyTyped

    private void JB_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_registrarActionPerformed
        String TituloL = JTF_TituloLP.getText();

        String autor = JTF_AutorP.getText();
        String añoPublicacion = JTF_AñoPublicacionP.getText();
        String isbn = JTF_ISBNP.getText();

        // Crear una nueva instancia de ModeloUsuario y asignarla a la variable nuevoUsuario
        ModeloRegistroLibros modeloRegistroLibros = new ModeloRegistroLibros(TituloL, autor, añoPublicacion, isbn);
        JOptionPane.showMessageDialog(null, "Devolucion con exito");


    }//GEN-LAST:event_JB_registrarActionPerformed

    private void JTF_AutorPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_AutorPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_AutorPKeyPressed

    private void JTF_AutorPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_AutorPKeyTyped
        if (JTF_AutorP.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTF_AutorPKeyTyped

    private void JB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_backActionPerformed
        VistaDeUsuariosIngresados VistaDeUsuariosIngresados = new VistaDeUsuariosIngresados();
        VistaDeUsuariosIngresados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_backActionPerformed

    private void JTF_AutorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_AutorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_AutorPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_Devoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_back;
    public javax.swing.JButton JB_registrar;
    public static javax.swing.JTextField JTF_AutorP;
    public static javax.swing.JTextField JTF_AñoPublicacionP;
    public static javax.swing.JTextField JTF_ISBNP;
    public static javax.swing.JTextField JTF_TituloLP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
