/*
 Doncente: Magda Pineda
Universidad Juan de castellanos 
Asignatura: Programacion Orientada A Objetos
Descripcion:Clase que reprenseta la interfaz Principal De Usuario
Fecha:28/04/2024
Autor: Daniel Mauricio Gil Sosa
 */
package vista;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.ModeloUsuario;

/**
 *
 * @author Lenovo
 */
public class VistaUsuario extends javax.swing.JFrame {

    private ModeloUsuario user;
    
    
    
    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario() {
        initComponents();
       
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_User = new javax.swing.JTextField();
        JP_Password = new javax.swing.JPasswordField();
        JB_crearUsuario = new javax.swing.JButton();
        JB_aceptar = new javax.swing.JButton();
        JC_mostrarContraseña = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTF_Clave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel3.setText("Contraseña:");

        JTF_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_UserKeyTyped(evt);
            }
        });

        JP_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JP_PasswordActionPerformed(evt);
            }
        });
        JP_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JP_PasswordKeyTyped(evt);
            }
        });

        JB_crearUsuario.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_crearUsuario.setText("Crear Usuario");
        JB_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_crearUsuarioActionPerformed(evt);
            }
        });

        JB_aceptar.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JB_aceptar.setText("Aceptar");
        JB_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_aceptarActionPerformed(evt);
            }
        });

        JC_mostrarContraseña.setFont(new java.awt.Font("Segoe UI Variable", 2, 12)); // NOI18N
        JC_mostrarContraseña.setText("Mostrar Contraseña");
        JC_mostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_mostrarContraseñaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 2, 24)); // NOI18N
        jLabel5.setText("LOGIN");

        JTF_Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ClaveActionPerformed(evt);
            }
        });
        JTF_Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_ClaveKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_User, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JP_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(JC_mostrarContraseña))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(JB_aceptar)
                        .addGap(59, 59, 59)
                        .addComponent(JB_crearUsuario)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JP_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JC_mostrarContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTF_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_aceptar)
                    .addComponent(JB_crearUsuario))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTF_UserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_UserKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) || Character.isWhitespace(evt.getKeyChar())) {
            evt.consume();

        }
        if (JTF_User.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_JTF_UserKeyTyped

    private void JP_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JP_PasswordKeyTyped
        if (JP_Password.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_JP_PasswordKeyTyped

    private void JB_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_crearUsuarioActionPerformed
        VistaCrear vistaCrear = new VistaCrear();
        vistaCrear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JB_crearUsuarioActionPerformed

    private void JB_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_aceptarActionPerformed
    String user = this.JTF_User.getText();
    String clave = this.JTF_Clave.getText();
    String userd = VistaCrear.JTF_NameUser.getText();
    String claved = VistaCrear.JTF_Clave.getText();
    
    if(user.equals(userd) && clave.equals(claved)){
        VistaFinal vistaFinal = new VistaFinal();
        vistaFinal.setVisible(true);
        this.setVisible(false);
    }else{
        
    }
    
    }//GEN-LAST:event_JB_aceptarActionPerformed

    private void JC_mostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_mostrarContraseñaActionPerformed
        if (JC_mostrarContraseña.isSelected()) {
            JP_Password.setEchoChar((char) 0);
        } else {
            JP_Password.setEchoChar('*');

        }
    }//GEN-LAST:event_JC_mostrarContraseñaActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void JP_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JP_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JP_PasswordActionPerformed

    private void JTF_ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_ClaveKeyTyped
         if (JP_Password.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_JTF_ClaveKeyTyped

    private void JTF_ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ClaveActionPerformed
           if (JC_mostrarContraseña.isSelected()) {
            JP_Password.setEchoChar((char) 0);
        } else {
            JP_Password.setEchoChar('*');

        }
    }//GEN-LAST:event_JTF_ClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_aceptar;
    public javax.swing.JButton JB_crearUsuario;
    public javax.swing.JCheckBox JC_mostrarContraseña;
    public javax.swing.JPasswordField JP_Password;
    public javax.swing.JTextField JTF_Clave;
    public javax.swing.JTextField JTF_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    public boolean Verif(){
        if((JTF_Clave.getText().equals(user.getContraseña()) && JTF_User.getText().equals(user.getUsuario()))){
            VistaFinal vistaFinal = new VistaFinal();
                vistaFinal.setVisible(true);
                this.setVisible(false);
            return true;
          
        }else{
            return false;
        }
    }
}
