/*
Doncente: Magda Pineda
Universidad Juan de castellanos 
Asignatura: Programacion Orientada A Objetos
Descripcion:Clase que reprenseta la interfaz Principal De usuario
Fecha:
Autor: Daniel Mauricio Gil Sosa
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class VistaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form VistaCalculadora
     */
    public VistaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RB_suma = new javax.swing.JRadioButton();
        RB_resta = new javax.swing.JRadioButton();
        RB_multiplicacion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        RB_division = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        JTF_Num2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTF_Result = new javax.swing.JTextField();
        JBT_Calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTF_Num1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RB_suma.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        RB_suma.setText("SUMA");
        RB_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_sumaActionPerformed(evt);
            }
        });

        RB_resta.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        RB_resta.setText("RESTA");

        RB_multiplicacion.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        RB_multiplicacion.setText("MULTIPLICACIÓN");
        RB_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_multiplicacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel4.setText("Bienvenido a calculadoraD");

        RB_division.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        RB_division.setText("DIVISIÓN");
        RB_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_divisionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel2.setText("Ingrese número");

        JTF_Num2.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JTF_Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_Num2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel3.setText("RESULTADO");

        JTF_Result.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N

        JBT_Calcular.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JBT_Calcular.setText("Calcular");
        JBT_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_CalcularActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        jLabel1.setText("Ingrese número");

        JTF_Num1.setFont(new java.awt.Font("Segoe UI Variable", 2, 18)); // NOI18N
        JTF_Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_Num1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTF_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RB_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RB_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RB_multiplicacion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(JTF_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RB_division, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBT_Calcular)
                        .addGap(277, 277, 277))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(JTF_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_suma)
                    .addComponent(RB_resta)
                    .addComponent(RB_multiplicacion)
                    .addComponent(RB_division))
                .addGap(31, 31, 31)
                .addComponent(JBT_Calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_sumaActionPerformed

    private void RB_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_multiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_multiplicacionActionPerformed

    private void RB_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_divisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_divisionActionPerformed

    private void JTF_Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_Num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_Num2ActionPerformed

    private void JBT_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_CalcularActionPerformed
        try {
            int Numero1, Numero2, result = 0;
            Numero1 = Integer.parseInt(JTF_Num1.getText());
            Numero2 = Integer.parseInt(JTF_Num2.getText());

            if (Numero1 < 0 || Numero2 < 0) {
                throw new IllegalArgumentException("Solo se admiten numeros positivos");
            }

            if (RB_suma.isSelected()) {
                result = Numero1 + Numero2;
            } else if (RB_resta.isSelected()) {
                result = Numero1 - Numero2;
            } else if (RB_multiplicacion.isSelected()) {
                result = Numero1 * Numero2;
            } else if (RB_division.isSelected()) {
                if (Numero2 == 0) {
                    throw new ArithmeticException("No podemos realizar esa division ");
                }
                result = Numero1 / Numero2;
            } else {
                JOptionPane.showMessageDialog(null, "Falta Operacion");
            }

            JTF_Result.setText(String.valueOf(result));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese números válidos en los campos de entrada");
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_JBT_CalcularActionPerformed

    private void JTF_Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_Num1ActionPerformed
        
    }//GEN-LAST:event_JTF_Num1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_Calcular;
    public javax.swing.JTextField JTF_Num1;
    public javax.swing.JTextField JTF_Num2;
    public javax.swing.JTextField JTF_Result;
    public javax.swing.JRadioButton RB_division;
    public javax.swing.JRadioButton RB_multiplicacion;
    public javax.swing.JRadioButton RB_resta;
    public javax.swing.JRadioButton RB_suma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
